USE NEXUSCCPAAS_AYTYCOREDB
GO

DECLARE @V_ID_PROJECT INT;
DECLARE @V_NU_TICKET INT;
DECLARE @V_NU_PACKAGE INT;

-------------------------------
SET @V_ID_PROJECT = 1071; --
SET @V_NU_TICKET = 1071;	 --
SET @V_NU_PACKAGE = 1;		 --
-------------------------------

-- VERIFICA SE O SCRIPT DE PACKAGE_LOG ESTÁ SENDO EXECUTADO NO CORE
IF NOT EXISTS (SELECT 1 FROM SYS.DATABASES WHERE DATABASE_ID = DB_ID() AND NAME LIKE '%AYTYCORE%') 
BEGIN    
	RAISERROR('#AYTY_EXCEPTION: OS SCRIPTS DE PACKAGE_LOG DEVEM SER EXECUTADOS EM BASES AYTYCORE.', 18, 1);  
	RETURN;    
END 	

--ATUALIZAÇÃO PARA INDICAR QUE O PACOTE FOI EXECUTADO COM SUCESSO ATÉ O ÚLTIMO SCRIPT
UPDATE
	PACKAGE_LOG
SET
	DT_FINISH=GETDATE(),
	WAS_COMPLETED=1
WHERE 
	NU_TICKET = @V_NU_TICKET AND
	NU_PACKAGE = @V_NU_PACKAGE AND
	ID_PROJECT = @V_ID_PROJECT;
