USE NEXUSCCPAAS_AYTYCOREDB
GO


DECLARE @V_ID_PROJECT INT;
DECLARE @V_NU_TICKET INT;
DECLARE @V_NU_PACKAGE INT;
DECLARE @V_WAS_COMPLETED BIT;
DECLARE @V_DE_ALTER_OBJECTS VARCHAR(MAX);
DECLARE @V_DE_OBS VARCHAR(MAX);
DECLARE @V_NU_TICKET_DEPEN VARCHAR(1000);
DECLARE @V_NU_PACKAGE_DEPEN VARCHAR(1000);
DECLARE @V_NU_CONTROL_DEPEN INT; 
DECLARE @V_QT_ATTEMPTS INT;
DECLARE @V_ID_PACKAGE_LOG INT;
DECLARE @V_ERROR_DEPEN BIT;


-----------------------------------------------------
SET @V_ID_PROJECT = 1071;    			        	-- EX: 441
SET @V_NU_TICKET = 137466;					   	-- EX: 35005
SET @V_NU_PACKAGE = 1;						   	-- NÚMERO DO PACOTE NO TICKET. EX: PRIMEIRO PACOTE DO TICKET NU_PACKAGE=1 , PACOTE COMPLEMENTAR NU_PACKAGE=2	
SET @V_DE_ALTER_OBJECTS='PROJECT,MAILING';						-- NOME DOS OBJETOS QUE FORAM ALTERADOS PELO SCRIPT, SEPARADOS POR ; . EX: 'SPR_RPT_TMO;CALL_TYPE;CALL'
SET @V_DE_OBS='OBSERVAÇÃO';

SET @V_NU_TICKET_DEPEN = '';	-- EX: '(35439)'   	-- NÚMEROS DOS TICKETS DOS QUAIS  ESTE DEPENDE.
SET @V_NU_PACKAGE_DEPEN = '';   -- EX: '(1,2)'     	-- NÚMEROS DOS PACOTES NO TICKET QUE ESTE DEPENDE 
-----------------------------------------------------

SET NOCOUNT ON;
SET @V_ERROR_DEPEN = 0;

-- VERIFICA SE O SCRIPT DE PACKAGE_LOG ESTÁ SENDO EXECUTADO NO CORE
IF NOT EXISTS (SELECT 1 FROM SYS.DATABASES WHERE DATABASE_ID = DB_ID() AND NAME LIKE '%AYTYCORE%') 
BEGIN    
	RAISERROR('#AYTY_EXCEPTION: OS SCRIPTS DE PACKAGE_LOG DEVEM SER EXECUTADOS EM BASES AYTYCORE.', 18, 1);  
	RETURN;    
END 	

-- VERIFICA SE EXISTE A TABELA DE LOG
IF OBJECT_ID('PACKAGE_LOG') IS NULL
BEGIN 
	CREATE TABLE DBO.PACKAGE_LOG (
		ID_PACKAGE_LOG INT PRIMARY KEY IDENTITY(1,1),	
		NU_TICKET INT,			-- EX: 35005
		QT_ATTEMPTS INT,		-- QUANTIDADE DE VEZES QUE EXECUTOU O MESMO PACOTE
		NU_PACKAGE INT,			-- NÚMERO DO PACOTE NO TICKET. EX: PRIMEIRO PACOTE DO TICKET NU_PACKAGE=1 , PACOTE COMPLEMENTAR NU_PACKAGE=2
		ID_PROJECT INT,			-- ESSE SCRIPT É EXECUTADO NO CORE, ENTÃO GUARDA O ID_PROJECT PARA SABER QUAL OPERAÇÃO O PACOTE VAI ALTERAR.
		DT_START DATETIME,		-- QUANDO EXECUTOU A PRIMEIRA VEZ O PACOTE.
		DT_LAST_TRY DATETIME,	-- ÚLTIMA TENTATIVA DE EXECUÇÃO DO PACOTE
		DT_FINISH DATETIME,		-- QUANDO TERMINOU DE EXECUTAR O PACOTE. VAI SER NULL SE DER ERRO EM ALGUM SCRIPT NO MEIO DO PACOTE. DEVE SER ATUALIZADO NO ÚLTIMO SCRIPT DO PACOTE.
		WAS_COMPLETED BIT,		-- 1: EXECUTOU ATÉ O FINAL , 0: ERRO EM ALGUM SCRIPT
		DE_ALTER_OBJECTS VARCHAR(MAX), -- NOME DOS OBJETOS QUE FORAM ALTERADOS PELO SCRIPT, SEPARADOS POR ; . EX: 'SPR_RPT_TMO;CALL_TYPE;CALL'
		DE_OBS VARCHAR(MAX)		-- EX: 'PACOTE PARA ALTERAR O RELATÓRIO TMO COM NOVO AGRUPAMENTO POR OPERADOR.'
	)  
		
    --INDICE PARA AJUDAR NA PERFORMANCE   
    CREATE NONCLUSTERED INDEX IX_NU_TICKET_PACKAGE_LOG ON PACKAGE_LOG(NU_TICKET, NU_PACKAGE)           
END       

-------------------------------------------------------------------------------------------------------------
--VERIFICA O PROGRAMADOR SETOU O Nº DO TICKET E PACOTE PARA INSERIR/ATUALIZAR INFORMAÇÃO DE LOG
-------------------------------------------------------------------------------------------------------------
IF(@V_NU_TICKET>0 AND  @V_NU_PACKAGE>0) 
BEGIN

	-- DESCOBRE SE JÁ EXECUTOU O PACOTE COM SUCESSO
	SELECT TOP 1
		@V_ID_PACKAGE_LOG = ID_PACKAGE_LOG,
		@V_WAS_COMPLETED = WAS_COMPLETED
	FROM
		PACKAGE_LOG
	WHERE
		NU_TICKET = @V_NU_TICKET AND
		NU_PACKAGE = @V_NU_PACKAGE AND
		ID_PROJECT = @V_ID_PROJECT
	ORDER BY DT_LAST_TRY
		
	IF (@V_ID_PACKAGE_LOG IS NOT NULL)
	BEGIN	
	    -- SE JÁ EXECUTOU ESSE PACOTE ANTES (COM OU SEM SUCESSO) INCREMENTA QT_ATTEMPTS EM 1, ATUALIZA A DATA DA ÚLTIMA TENTATIVA 
		UPDATE PACKAGE_LOG
		SET
			QT_ATTEMPTS=ISNULL(QT_ATTEMPTS,0)+1,
			DT_LAST_TRY=GETDATE()
		WHERE
			ID_PACKAGE_LOG=@V_ID_PACKAGE_LOG
			
		--SE JÁ RODOU ESSE PACOTE COM SUCESSO ANTES GERA EXCEÇÃO.
		IF(@V_WAS_COMPLETED = 1)
		BEGIN
			RAISERROR('#AYTY_EXCEPTION: ESTE PACOTE JÁ FOI EXECUTADO ANTES!', 18, 1);  
			RETURN;   
		END 	
	END
			
END
ELSE -- SE ESQUECEU DE SETAR O NÚMERO DO TICKET OU DO PACOTE
BEGIN    
	RAISERROR('#AYTY_EXCEPTION: NÚMERO DE PACOTE OU DE TICKET INCORRETO.', 18, 1);  
	RETURN;    
END 
    
------------------------------------------------------------------------------------------------
-- VERIFICA SE ESTE PACOTE TEM DEPENDÊNCIA DE OUTRO E SE ESTE OUTRO JÁ FOI EXECUTADO COM SUCESSO
------------------------------------------------------------------------------------------------
IF (@V_NU_TICKET_DEPEN<>'' AND @V_NU_PACKAGE_DEPEN<>'')
--TEM DEPENDÊNCIA
BEGIN

	CREATE TABLE #TMP_DEPEN ( -- TABELA TEMPORÁRIA QUE GUARDA OS PACOTES DOS QUAIS ESTE DEPENDE
		ID_PACKAGE_LOG INT,
		WAS_COMPLETED BIT
	);
	
	-- INSERE OS PACOTES DE DEPENDENCIA NA TABELA TEMPORÁRIA
	EXEC('
		INSERT INTO #TMP_DEPEN
		SELECT
			ID_PACKAGE_LOG,
			WAS_COMPLETED
		FROM
			PACKAGE_LOG
		WHERE
			NU_TICKET  IN '+@V_NU_TICKET_DEPEN+'  AND
			NU_PACKAGE IN '+@V_NU_PACKAGE_DEPEN);
			
	SET	@V_NU_CONTROL_DEPEN = @@ROWCOUNT; -- 0 = TEM DEPENDENCIA E NÃO ACHOU NO LOG   /    MAIOR QUE 0 = TEM DEPENDENCIA E ACHOU NO LOG 
			
	-- SE TEM DEPENDÊNCIA E A DEPENDÊNCIA NÃO ESTÁ NO LOG = ERRO POIS NÃO EXECUTOU AS DEPENDENCIAS			
	IF (@V_NU_CONTROL_DEPEN <= 0 )  
		SET @V_ERROR_DEPEN = 1; 
	ELSE
	BEGIN
		--SE TEM DEPENDÊNCIA E A DEPENDÊNCIA ESTÁ NO LOG, NECESSÁRIO VERIFICAR SE TODAS FORAM EXECUTADAS ATÉ O FIM
		SELECT @V_NU_CONTROL_DEPEN = COUNT(ID_PACKAGE_LOG)
		FROM 
			#TMP_DEPEN
		WHERE 
			WAS_COMPLETED =0;	
			
		IF (@V_NU_CONTROL_DEPEN > 0 )	
			--TEM DEPÊNDENCIAS, AS DEPENDÊNCIAS ESTÃO NO LOG MAS ALGUMA NÃO EXECUTOU ATÉ O FIM = ERRO
			SET @V_ERROR_DEPEN = 1;			
	END
	
	--DROP NA TABELA TEMPORÁRIA
	DROP TABLE #TMP_DEPEN;		
	
	--EXCEÇÃO NA TELA.	
	IF (@V_ERROR_DEPEN=1)
	BEGIN
		RAISERROR('#AYTY_EXCEPTION: ESTE PACOTE TEM DEPENDÊNCIAS NÃO EXECUTADAS!', 18, 1);  
		RETURN;      		
	END	
	
END

--SE CHEGOU AQUI, É PORQUE O PACOTE AINDA NÃO FOI EXECUTADO COM SUCESSO E NÃO TEM DEPENDENCIAS PENDENTES.

IF(@V_ID_PROJECT > 0) --VERIFICAR SE O PROGRAMADOR COLOCOU O ID_PROJECT
BEGIN	
	--VERIFICAR SE EXISTE ALGUM REGISTRO DESTE PACOTE COM WAS_COMPLETED = 0, PARA SABER SE É NECESSÁRIO O INSERT
	IF(@V_ID_PACKAGE_LOG IS NULL)
	BEGIN
		INSERT INTO PACKAGE_LOG (
					NU_TICKET,		
					QT_ATTEMPTS,	
					NU_PACKAGE,	
					ID_PROJECT,	
					DT_START,
					DT_LAST_TRY,
					DT_FINISH,
					WAS_COMPLETED,
					DE_ALTER_OBJECTS,
					DE_OBS		
				)
				VALUES (
					@V_NU_TICKET,
					1,
					@V_NU_PACKAGE,
					@V_ID_PROJECT,
					GETDATE(),
					GETDATE(),
					NULL,
					0,
					@V_DE_ALTER_OBJECTS,
					@V_DE_OBS		
				)
		END				
END			
ELSE
	RAISERROR('#AYTY_EXCEPTION: É NECESSÁRIO INFORMAR O ID_PROJECT!', 18, 1);  

SET NOCOUNT OFF

